# name: Build PyInstaller Executables for Linux

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     # Checkout the repository
#     - name: Checkout code
#       uses: actions/checkout@v3

#     # Set up Python
#     - name: Set up Python
#       uses: actions/setup-python@v4
#       with:
#         python-version: 3.x

#     # Install dependencies
#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt
#         pip install pyinstaller

#     # Build with PyInstaller
#     - name: Build with PyInstaller
#       run: |
#         pyinstaller --onefile --noconsole \
#           --add-data "templates:templates" \
#           --add-data "static:static" \
#           --add-data "logo.ico:." \
#           --icon=logo.png metadataEditor.py

#     # Upload the artifact (executable)
#     - name: Upload executable
#       uses: actions/upload-artifact@v4
#       with:
#         name: flask-app-linux
#         path: dist/metadataEditor
